import type { ImageSourcePropType } from 'react-native';

import { getRemoteAssetUrl, remoteAssetsConfig } from '../config/remoteAssets';

const registry: Record<string, ImageSourcePropType> = {
  'lessons/at-school/classroom/images/baby.png': require('../assets/lessons/at-school/classroom/images/baby.png'),
  'lessons/at-school/classroom/images/background.png': require('../assets/lessons/at-school/classroom/images/background.png'),
  'lessons/at-school/classroom/images/board.png': require('../assets/lessons/at-school/classroom/images/board.png'),
  'lessons/at-school/classroom/images/chair.png': require('../assets/lessons/at-school/classroom/images/chair.png'),
  'lessons/at-school/classroom/images/classroom.png': require('../assets/lessons/at-school/classroom/images/classroom.png'),
  'lessons/at-school/classroom/images/desk.png': require('../assets/lessons/at-school/classroom/images/desk.png'),
  'lessons/at-school/classroom/images/hand.png': require('../assets/lessons/at-school/classroom/images/hand.png'),
  'lessons/at-school/classroom/images/teacher.png': require('../assets/lessons/at-school/classroom/images/teacher.png'),
  'lessons/at-school/school-supplies/images/baby.png': require('../assets/lessons/at-school/school-supplies/images/baby.png'),
  'lessons/at-school/school-supplies/images/background.png': require('../assets/lessons/at-school/school-supplies/images/background.png'),
  'lessons/at-school/school-supplies/images/book.png': require('../assets/lessons/at-school/school-supplies/images/book.png'),
  'lessons/at-school/school-supplies/images/circle.png': require('../assets/lessons/at-school/school-supplies/images/circle.png'),
  'lessons/at-school/school-supplies/images/crayon.png': require('../assets/lessons/at-school/school-supplies/images/crayon.png'),
  'lessons/at-school/school-supplies/images/eraser.png': require('../assets/lessons/at-school/school-supplies/images/eraser.png'),
  'lessons/at-school/school-supplies/images/notebook.png': require('../assets/lessons/at-school/school-supplies/images/notebook.png'),
  'lessons/at-school/school-supplies/images/pencil.png': require('../assets/lessons/at-school/school-supplies/images/pencil.png'),
  'lessons/at-school/school-supplies/images/ruler.png': require('../assets/lessons/at-school/school-supplies/images/ruler.png'),
  'lessons/at-school/teacher-instructions/images/baby.png': require('../assets/lessons/at-school/teacher-instructions/images/baby.png'),
  'lessons/at-school/teacher-instructions/images/background.png': require('../assets/lessons/at-school/teacher-instructions/images/background.png'),
  'lessons/at-school/teacher-instructions/images/book.png': require('../assets/lessons/at-school/teacher-instructions/images/book.png'),
  'lessons/at-school/teacher-instructions/images/box.png': require('../assets/lessons/at-school/teacher-instructions/images/box.png'),
  'lessons/at-school/teacher-instructions/images/crayon.png': require('../assets/lessons/at-school/teacher-instructions/images/crayon.png'),
  'lessons/at-school/teacher-instructions/images/hand.png': require('../assets/lessons/at-school/teacher-instructions/images/hand.png'),
  'lessons/at-school/teacher-instructions/images/notebook.png': require('../assets/lessons/at-school/teacher-instructions/images/notebook.png'),
  'lessons/at-school/teacher-instructions/images/pencil.png': require('../assets/lessons/at-school/teacher-instructions/images/pencil.png'),
  'lessons/at-school/teacher-instructions/images/teacher.png': require('../assets/lessons/at-school/teacher-instructions/images/teacher.png'),
  'lessons/playtime/playground/images/baby.png': require('../assets/lessons/playtime/playground/images/baby.png'),
  'lessons/playtime/playground/images/background.png': require('../assets/lessons/playtime/playground/images/background.png'),
  'lessons/playtime/playground/images/ball.png': require('../assets/lessons/playtime/playground/images/ball.png'),
  'lessons/playtime/playground/images/jump.png': require('../assets/lessons/playtime/playground/images/jump.png'),
  'lessons/playtime/playground/images/playground.png': require('../assets/lessons/playtime/playground/images/playground.png'),
  'lessons/playtime/playground/images/run.png': require('../assets/lessons/playtime/playground/images/run.png'),
  'lessons/playtime/playground/images/sandbox.png': require('../assets/lessons/playtime/playground/images/sandbox.png'),
  'lessons/playtime/playground/images/seesaw.png': require('../assets/lessons/playtime/playground/images/seesaw.png'),
  'lessons/playtime/playground/images/slide.png': require('../assets/lessons/playtime/playground/images/slide.png'),
  'lessons/playtime/playground/images/swing.png': require('../assets/lessons/playtime/playground/images/swing.png'),
  'lessons/playtime/playground/images/turn.png': require('../assets/lessons/playtime/playground/images/turn.png'),
  'lessons/playtime/friend-games/images/baby.png': require('../assets/lessons/playtime/friend-games/images/baby.png'),
  'lessons/playtime/friend-games/images/background.png': require('../assets/lessons/playtime/friend-games/images/background.png'),
  'lessons/playtime/friend-games/images/blocks.png': require('../assets/lessons/playtime/friend-games/images/blocks.png'),
  'lessons/playtime/friend-games/images/bucket.png': require('../assets/lessons/playtime/friend-games/images/bucket.png'),
  'lessons/playtime/friend-games/images/friend.png': require('../assets/lessons/playtime/friend-games/images/friend.png'),
  'lessons/playtime/friend-games/images/kite.png': require('../assets/lessons/playtime/friend-games/images/kite.png'),
  'lessons/playtime/friend-games/images/play-together.png': require('../assets/lessons/playtime/friend-games/images/play-together.png'),
  'lessons/playtime/friend-games/images/rope.png': require('../assets/lessons/playtime/friend-games/images/rope.png'),
  'lessons/playtime/friend-games/images/share.png': require('../assets/lessons/playtime/friend-games/images/share.png'),
  'lessons/playtime/friend-games/images/toy.png': require('../assets/lessons/playtime/friend-games/images/toy.png'),
  'lessons/playtime/friend-games/images/wait.png': require('../assets/lessons/playtime/friend-games/images/wait.png'),
  'lessons/playtime/playtime-rest/images/baby.png': require('../assets/lessons/playtime/playtime-rest/images/baby.png'),
  'lessons/playtime/playtime-rest/images/background.png': require('../assets/lessons/playtime/playtime-rest/images/background.png'),
  'lessons/playtime/playtime-rest/images/bench.png': require('../assets/lessons/playtime/playtime-rest/images/bench.png'),
  'lessons/playtime/playtime-rest/images/bottle.png': require('../assets/lessons/playtime/playtime-rest/images/bottle.png'),
  'lessons/playtime/playtime-rest/images/face.png': require('../assets/lessons/playtime/playtime-rest/images/face.png'),
  'lessons/playtime/playtime-rest/images/mouth.png': require('../assets/lessons/playtime/playtime-rest/images/mouth.png'),
  'lessons/playtime/playtime-rest/images/shade.png': require('../assets/lessons/playtime/playtime-rest/images/shade.png'),
  'lessons/playtime/playtime-rest/images/snack.png': require('../assets/lessons/playtime/playtime-rest/images/snack.png'),
  'lessons/playtime/playtime-rest/images/towel.png': require('../assets/lessons/playtime/playtime-rest/images/towel.png'),
  'lessons/playtime/playtime-rest/images/water.png': require('../assets/lessons/playtime/playtime-rest/images/water.png'),
  'lessons/lunch-time/lunch-box/images/baby.png': require('../assets/lessons/lunch-time/lunch-box/images/baby.png'),
  'lessons/lunch-time/lunch-box/images/background.png': require('../assets/lessons/lunch-time/lunch-box/images/background.png'),
  'lessons/lunch-time/lunch-box/images/bowl.png': require('../assets/lessons/lunch-time/lunch-box/images/bowl.png'),
  'lessons/lunch-time/lunch-box/images/fork.png': require('../assets/lessons/lunch-time/lunch-box/images/fork.png'),
  'lessons/lunch-time/lunch-box/images/lunchbox.png': require('../assets/lessons/lunch-time/lunch-box/images/lunchbox.png'),
  'lessons/lunch-time/lunch-box/images/mouth.png': require('../assets/lessons/lunch-time/lunch-box/images/mouth.png'),
  'lessons/lunch-time/lunch-box/images/open-lunchbox.png': require('../assets/lessons/lunch-time/lunch-box/images/open-lunchbox.png'),
  'lessons/lunch-time/lunch-box/images/rice.png': require('../assets/lessons/lunch-time/lunch-box/images/rice.png'),
  'lessons/lunch-time/lunch-box/images/soup.png': require('../assets/lessons/lunch-time/lunch-box/images/soup.png'),
  'lessons/lunch-time/lunch-box/images/spoon.png': require('../assets/lessons/lunch-time/lunch-box/images/spoon.png'),
  'lessons/lunch-time/lunch-table/images/baby.png': require('../assets/lessons/lunch-time/lunch-table/images/baby.png'),
  'lessons/lunch-time/lunch-table/images/background.png': require('../assets/lessons/lunch-time/lunch-table/images/background.png'),
  'lessons/lunch-time/lunch-table/images/chair.png': require('../assets/lessons/lunch-time/lunch-table/images/chair.png'),
  'lessons/lunch-time/lunch-table/images/cup.png': require('../assets/lessons/lunch-time/lunch-table/images/cup.png'),
  'lessons/lunch-time/lunch-table/images/friend.png': require('../assets/lessons/lunch-time/lunch-table/images/friend.png'),
  'lessons/lunch-time/lunch-table/images/fruit.png': require('../assets/lessons/lunch-time/lunch-table/images/fruit.png'),
  'lessons/lunch-time/lunch-table/images/napkin.png': require('../assets/lessons/lunch-time/lunch-table/images/napkin.png'),
  'lessons/lunch-time/lunch-table/images/sit-at-table.png': require('../assets/lessons/lunch-time/lunch-table/images/sit-at-table.png'),
  'lessons/lunch-time/lunch-table/images/table.png': require('../assets/lessons/lunch-time/lunch-table/images/table.png'),
  'lessons/lunch-time/lunch-table/images/thank-you.png': require('../assets/lessons/lunch-time/lunch-table/images/thank-you.png'),
  'lessons/lunch-time/after-lunch/images/baby.png': require('../assets/lessons/lunch-time/after-lunch/images/baby.png'),
  'lessons/lunch-time/after-lunch/images/background.png': require('../assets/lessons/lunch-time/after-lunch/images/background.png'),
  'lessons/lunch-time/after-lunch/images/crumbs.png': require('../assets/lessons/lunch-time/after-lunch/images/crumbs.png'),
  'lessons/lunch-time/after-lunch/images/hands.png': require('../assets/lessons/lunch-time/after-lunch/images/hands.png'),
  'lessons/lunch-time/after-lunch/images/plate.png': require('../assets/lessons/lunch-time/after-lunch/images/plate.png'),
  'lessons/lunch-time/after-lunch/images/sink.png': require('../assets/lessons/lunch-time/after-lunch/images/sink.png'),
  'lessons/lunch-time/after-lunch/images/soap.png': require('../assets/lessons/lunch-time/after-lunch/images/soap.png'),
  'lessons/lunch-time/after-lunch/images/table.png': require('../assets/lessons/lunch-time/after-lunch/images/table.png'),
  'lessons/lunch-time/after-lunch/images/towel.png': require('../assets/lessons/lunch-time/after-lunch/images/towel.png'),
  'lessons/lunch-time/after-lunch/images/trash-bin.png': require('../assets/lessons/lunch-time/after-lunch/images/trash-bin.png'),
  'lessons/afternoon-home/going-home/images/baby.png': require('../assets/lessons/afternoon-home/going-home/images/baby.png'),
  'lessons/afternoon-home/going-home/images/background.png': require('../assets/lessons/afternoon-home/going-home/images/background.png'),
  'lessons/afternoon-home/going-home/images/bag.png': require('../assets/lessons/afternoon-home/going-home/images/bag.png'),
  'lessons/afternoon-home/going-home/images/bottle.png': require('../assets/lessons/afternoon-home/going-home/images/bottle.png'),
  'lessons/afternoon-home/going-home/images/door.png': require('../assets/lessons/afternoon-home/going-home/images/door.png'),
  'lessons/afternoon-home/going-home/images/folder.png': require('../assets/lessons/afternoon-home/going-home/images/folder.png'),
  'lessons/afternoon-home/going-home/images/goodbye.png': require('../assets/lessons/afternoon-home/going-home/images/goodbye.png'),
  'lessons/afternoon-home/going-home/images/jacket.png': require('../assets/lessons/afternoon-home/going-home/images/jacket.png'),
  'lessons/afternoon-home/going-home/images/line.png': require('../assets/lessons/afternoon-home/going-home/images/line.png'),
  'lessons/afternoon-home/going-home/images/teacher.png': require('../assets/lessons/afternoon-home/going-home/images/teacher.png'),
  'lessons/afternoon-home/ride-home/images/baby.png': require('../assets/lessons/afternoon-home/ride-home/images/baby.png'),
  'lessons/afternoon-home/ride-home/images/background.png': require('../assets/lessons/afternoon-home/ride-home/images/background.png'),
  'lessons/afternoon-home/ride-home/images/bus-door.png': require('../assets/lessons/afternoon-home/ride-home/images/bus-door.png'),
  'lessons/afternoon-home/ride-home/images/bus.png': require('../assets/lessons/afternoon-home/ride-home/images/bus.png'),
  'lessons/afternoon-home/ride-home/images/home.png': require('../assets/lessons/afternoon-home/ride-home/images/home.png'),
  'lessons/afternoon-home/ride-home/images/road.png': require('../assets/lessons/afternoon-home/ride-home/images/road.png'),
  'lessons/afternoon-home/ride-home/images/seat-belt.png': require('../assets/lessons/afternoon-home/ride-home/images/seat-belt.png'),
  'lessons/afternoon-home/ride-home/images/traffic-light.png': require('../assets/lessons/afternoon-home/ride-home/images/traffic-light.png'),
  'lessons/afternoon-home/ride-home/images/window.png': require('../assets/lessons/afternoon-home/ride-home/images/window.png'),
  'lessons/afternoon-home/home-arrival/images/baby.png': require('../assets/lessons/afternoon-home/home-arrival/images/baby.png'),
  'lessons/afternoon-home/home-arrival/images/background.png': require('../assets/lessons/afternoon-home/home-arrival/images/background.png'),
  'lessons/afternoon-home/home-arrival/images/family.png': require('../assets/lessons/afternoon-home/home-arrival/images/family.png'),
  'lessons/afternoon-home/home-arrival/images/hands.png': require('../assets/lessons/afternoon-home/home-arrival/images/hands.png'),
  'lessons/afternoon-home/home-arrival/images/home.png': require('../assets/lessons/afternoon-home/home-arrival/images/home.png'),
  'lessons/afternoon-home/home-arrival/images/hug-family.png': require('../assets/lessons/afternoon-home/home-arrival/images/hug-family.png'),
  'lessons/afternoon-home/home-arrival/images/shelf.png': require('../assets/lessons/afternoon-home/home-arrival/images/shelf.png'),
  'lessons/afternoon-home/home-arrival/images/shoes.png': require('../assets/lessons/afternoon-home/home-arrival/images/shoes.png'),
  'lessons/afternoon-home/home-arrival/images/soap.png': require('../assets/lessons/afternoon-home/home-arrival/images/soap.png'),
  'lessons/afternoon-home/home-arrival/images/towel.png': require('../assets/lessons/afternoon-home/home-arrival/images/towel.png'),
  'lessons/morning-routine/bathroom/images/baby.png': require('../assets/lessons/morning-routine/bathroom/images/baby.png'),
  'lessons/morning-routine/bathroom/images/background.png': require('../assets/lessons/morning-routine/bathroom/images/background.png'),
  'lessons/morning-routine/bathroom/images/mirror.png': require('../assets/lessons/morning-routine/bathroom/images/mirror.png'),
  'lessons/morning-routine/bathroom/images/sink.png': require('../assets/lessons/morning-routine/bathroom/images/sink.png'),
  'lessons/morning-routine/bathroom/images/soap.png': require('../assets/lessons/morning-routine/bathroom/images/soap.png'),
  'lessons/morning-routine/bathroom/images/toothbrush.png': require('../assets/lessons/morning-routine/bathroom/images/toothbrush.png'),
  'lessons/morning-routine/bathroom/images/toothpaste.png': require('../assets/lessons/morning-routine/bathroom/images/toothpaste.png'),
  'lessons/morning-routine/bathroom/images/towel.png': require('../assets/lessons/morning-routine/bathroom/images/towel.png'),
  'lessons/morning-routine/bathroom/images/water.png': require('../assets/lessons/morning-routine/bathroom/images/water.png'),
  'lessons/morning-routine/breakfast/images/apple.png': require('../assets/lessons/morning-routine/breakfast/images/apple.png'),
  'lessons/morning-routine/breakfast/images/baby.png': require('../assets/lessons/morning-routine/breakfast/images/baby.png'),
  'lessons/morning-routine/breakfast/images/background.png': require('../assets/lessons/morning-routine/breakfast/images/background.png'),
  'lessons/morning-routine/breakfast/images/banana.png': require('../assets/lessons/morning-routine/breakfast/images/banana.png'),
  'lessons/morning-routine/breakfast/images/bread.png': require('../assets/lessons/morning-routine/breakfast/images/bread.png'),
  'lessons/morning-routine/breakfast/images/cup.png': require('../assets/lessons/morning-routine/breakfast/images/cup.png'),
  'lessons/morning-routine/breakfast/images/egg.png': require('../assets/lessons/morning-routine/breakfast/images/egg.png'),
  'lessons/morning-routine/breakfast/images/milk.png': require('../assets/lessons/morning-routine/breakfast/images/milk.png'),
  'lessons/morning-routine/breakfast/images/plate.png': require('../assets/lessons/morning-routine/breakfast/images/plate.png'),
  'lessons/morning-routine/go-to-school/images/baby.png': require('../assets/lessons/morning-routine/go-to-school/images/baby.png'),
  'lessons/morning-routine/go-to-school/images/background.png': require('../assets/lessons/morning-routine/go-to-school/images/background.png'),
  'lessons/morning-routine/go-to-school/images/bag.png': require('../assets/lessons/morning-routine/go-to-school/images/bag.png'),
  'lessons/morning-routine/go-to-school/images/book.png': require('../assets/lessons/morning-routine/go-to-school/images/book.png'),
  'lessons/morning-routine/go-to-school/images/bus.png': require('../assets/lessons/morning-routine/go-to-school/images/bus.png'),
  'lessons/morning-routine/go-to-school/images/lunchbox.png': require('../assets/lessons/morning-routine/go-to-school/images/lunchbox.png'),
  'lessons/morning-routine/go-to-school/images/school.png': require('../assets/lessons/morning-routine/go-to-school/images/school.png'),
  'lessons/morning-routine/go-to-school/images/shoes.png': require('../assets/lessons/morning-routine/go-to-school/images/shoes.png'),
  'lessons/morning-routine/go-to-school/images/uniform.png': require('../assets/lessons/morning-routine/go-to-school/images/uniform.png'),
  'lessons/morning-routine/bedroom/images/baby.png': require('../assets/lessons/morning-routine/bedroom/images/baby.png'),
  'lessons/morning-routine/bedroom/images/background.png': require('../assets/lessons/morning-routine/bedroom/images/background.png'),
  'lessons/morning-routine/bedroom/images/bed.png': require('../assets/lessons/morning-routine/bedroom/images/bed.png'),
  'lessons/morning-routine/bedroom/images/blanket.png': require('../assets/lessons/morning-routine/bedroom/images/blanket.png'),
  'lessons/morning-routine/bedroom/images/box.png': require('../assets/lessons/morning-routine/bedroom/images/box.png'),
  'lessons/morning-routine/bedroom/images/clock.png': require('../assets/lessons/morning-routine/bedroom/images/clock.png'),
  'lessons/morning-routine/bedroom/images/doll.png': require('../assets/lessons/morning-routine/bedroom/images/doll.png'),
  'lessons/morning-routine/bedroom/images/lamp.png': require('../assets/lessons/morning-routine/bedroom/images/lamp.png'),
  'lessons/morning-routine/bedroom/images/pillow.png': require('../assets/lessons/morning-routine/bedroom/images/pillow.png'),
  'lessons/morning-routine/bedroom/images/socks.png': require('../assets/lessons/morning-routine/bedroom/images/socks.png'),
  'lessons/morning-routine/bedroom/images/sun.png': require('../assets/lessons/morning-routine/bedroom/images/sun.png'),
};

/**
 * Resolves a string path from data into a bundled React Native ImageSource.
 * Falls back to uri if the string is a valid remote/local URI.
 */
export function resolveAsset(source: string): ImageSourcePropType | undefined {
  if (remoteAssetsConfig.preferRemoteImages) {
    const remoteAssetUrl = getRemoteAssetUrl(source);
    if (remoteAssetUrl) {
      return { uri: remoteAssetUrl };
    }
  }

  if (registry[source]) {
    return registry[source];
  }

  if (/^(https?:|file:|content:|data:)/u.test(source)) {
    return { uri: source };
  }

  return undefined;
}
