import type { ImageRequireSource } from 'react-native';

/** Generated by scripts/generateMissingAudio.mjs. Do not edit manually. */
export const generatedUiAudioRegistry: Record<string, ImageRequireSource> = {
  "ui/audio/en-GB/neural2-c-r1/kid_lock_premium_bf7ed6cb.wav": require("../assets/ui/audio/en-GB/neural2-c-r1/kid_lock_premium_bf7ed6cb.wav"),
  "ui/audio/en-GB/neural2-c-r1/kid_lock_progress_d762101e.wav": require("../assets/ui/audio/en-GB/neural2-c-r1/kid_lock_progress_d762101e.wav"),
  "ui/audio/en-GB/neural2-c-r1/kid_lock_resolving_804ccf69.wav": require("../assets/ui/audio/en-GB/neural2-c-r1/kid_lock_resolving_804ccf69.wav"),
  "ui/audio/en-US/neural2-c-r1/kid_lock_premium_bf7ed6cb.wav": require("../assets/ui/audio/en-US/neural2-c-r1/kid_lock_premium_bf7ed6cb.wav"),
  "ui/audio/en-US/neural2-c-r1/kid_lock_progress_d762101e.wav": require("../assets/ui/audio/en-US/neural2-c-r1/kid_lock_progress_d762101e.wav"),
  "ui/audio/en-US/neural2-c-r1/kid_lock_resolving_804ccf69.wav": require("../assets/ui/audio/en-US/neural2-c-r1/kid_lock_resolving_804ccf69.wav"),
  "ui/audio/vi/kid_lock_premium_9eb2b4f6.wav": require("../assets/ui/audio/vi/kid_lock_premium_9eb2b4f6.wav"),
  "ui/audio/vi/kid_lock_progress_d8b53f77.wav": require("../assets/ui/audio/vi/kid_lock_progress_d8b53f77.wav"),
  "ui/audio/vi/kid_lock_resolving_7b714a40.wav": require("../assets/ui/audio/vi/kid_lock_resolving_7b714a40.wav"),
};
