export const colors = {
  background: '#EAF8FF',
  backgroundCool: '#DDF5FF',
  backgroundWarm: '#FFF8EC',
  surface: '#FFFFFF',
  surfaceSoft: '#FFF4D8',
  surfaceBlue: '#F2FBFF',
  primary: '#28BFB2',
  primaryDark: '#117B78',
  primarySoft: '#CFF7F1',
  secondary: '#FFD34D',
  secondaryDark: '#C88712',
  secondarySoft: '#FFF2B8',
  accent: '#FF7B5F',
  accentDark: '#D94B36',
  accentSoft: '#FFE1D8',
  alert: '#EF4444',
  lavender: '#DCD7FF',
  mint: '#BFF3D4',
  green: '#74D889',
  sky: '#AEE7FF',
  skyDeep: '#4DB7F2',
  cream: '#FFF8EC',
  border: '#D7EEF8',
  borderWarm: '#F3DDA8',
  shadow: '#5CA6C5',
  warmShadow: '#D7A03F',
  text: '#334155',
  textSoft: '#64748B',
  muted: '#94A3B8',
  white: '#FFFFFF',
  transparent: 'transparent',
} as const;

export type ColorToken = keyof typeof colors;
