# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SKidsEnglish' do
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    firebase_header_path = File.join(installer.sandbox.root, 'Firebase', 'CoreOnly', 'Sources', 'Firebase.h')
    if File.exist?(firebase_header_path)
      File.chmod(0o644, firebase_header_path)
      firebase_header = File.read(firebase_header_path)
      firebase_header.gsub!(
        '      #import <FirebaseAuth/FirebaseAuth-Swift.h>',
        "      #if __has_include(<FirebaseAuth/FirebaseAuth-Swift.h>)\n        #import <FirebaseAuth/FirebaseAuth-Swift.h>\n      #endif"
      )
      File.write(firebase_header_path, firebase_header)
    end
  end
end
