export const CLOUD_PROGRESS_SYNC_CONSENT_VERSION = 1;
export const CLOUD_PROGRESS_SCHEMA_VERSION = 1;
export const CLOUD_PROGRESS_DOCUMENT_ID = 'current';
export const CLOUD_PARENT_SETTINGS_SCHEMA_VERSION = 1;
export const CLOUD_PARENT_SETTINGS_DOCUMENT_ID = 'current';
