import { type SKidsIconName } from '../assets/icons/skids';
import type { Lesson, Scene } from '../types/lesson';

const sceneIconById: Record<string, SKidsIconName> = {
  'after-lunch': 'afterLunch',
  'animal-gate': 'animalGate',
  'angry-and-scared': 'angryScared',
  'arms-and-hands': 'armsHands',
  'bath-finish': 'bathFinish',
  'bath-prep': 'bathPrep',
  'bath-rinse': 'bathRinse',
  'beach-bag': 'beachBag',
  bathroom: 'bathroom',
  bedroom: 'bedroom',
  'bedtime-story': 'bedtimeStory',
  'book-corner': 'bookCorner',
  'body-boundaries': 'bodyBoundaries',
  'body-needs': 'bodyNeeds',
  'body-signals': 'bodySignals',
  'bring-it-back': 'bringItBack',
  breakfast: 'breakfast',
  'checkout-counter': 'supermarketCheckout',
  'calm-room': 'calmRoom',
  'care-items': 'careItems',
  classroom: 'classroom',
  'clear-dinner': 'clearDinner',
  'clean-and-private': 'cleanPrivate',
  'clinic-room': 'clinicRoom',
  'choose-clothes': 'chooseClothes',
  'choose-the-ball': 'chooseTheBall',
  'notice-the-muddy-paws': 'noticeMuddyPaws',
  'comfort-corner': 'comfortCorner',
  'cough-and-sneeze-care': 'coughSneezeCare',
  'creative-play': 'creativePlay',
  'dinner-cleanup': 'dinnerCleanup',
  'dinner-prep': 'dinnerPrep',
  'dinner-table': 'dinnerTable',
  'excited-and-proud': 'excitedProud',
  'face-and-hair-care': 'faceHairCare',
  'friend-games': 'friendGames',
  'family-visit': 'familyVisit',
  'fill-the-bowl': 'fillTheBowl',
  'hear-the-kitten': 'hearTheKitten',
  'farm-yard': 'farmYard',
  'fasteners-and-shoes': 'fastenersShoes',
  'flower-visitors': 'flowerVisitors',
  'fresh-foods': 'freshFoods',
  'first-watering': 'firstWatering',
  'find-the-ripe-ones': 'findTheRipeOnes',
  'garden-help': 'gardenHelp',
  'go-to-school': 'goToSchool',
  'goodbye-home': 'goodbyeHome',
  'going-home': 'goingHome',
  'health-check': 'healthCheck',
  'check-the-hiding-spots': 'checkHidingSpots',
  'happy-and-sad': 'happySad',
  'hearing-world': 'hearingWorld',
  'head-and-face': 'headFace',
  'home-arrival': 'homeArrival',
  'home-toy-corner': 'homeToyCorner',
  'library-card': 'libraryCard',
  'legs-and-feet': 'legsFeet',
  'lunch-box': 'lunchBox',
  'lunch-table': 'lunchTable',
  'medicine-care': 'medicineCare',
  'meet-the-puppy': 'meetThePuppy',
  'new-leaf-and-sunlight': 'newLeafSunlight',
  'park-entrance': 'parkEntrance',
  'park-games': 'parkGames',
  'park-picnic': 'parkPicnic',
  'pain-and-help': 'painHelp',
  'party-games': 'partyGames',
  'party-prep': 'partyPrep',
  'party-table': 'partyTable',
  playground: 'playground',
  'playtime-rest': 'playtimeRest',
  'put-on-clothes': 'putOnClothes',
  'puppy-eats': 'puppyEats',
  'quiet-garden-watch': 'quietGardenWatch',
  'rainy-day-care': 'rainyDayCare',
  'rinse-and-drain': 'rinseAndDrain',
  'wash-the-paws': 'washThePaws',
  'roll-and-catch': 'rollAndCatch',
  'plant-the-seed': 'plantTheSeed',
  'pick-gently': 'pickGently',
  'prepare-the-pot': 'prepareThePot',
  school: 'school',
  'school-supplies': 'schoolSupplies',
  'sand-play': 'beachSand',
  'sea-safety': 'beachSafety',
  'teacher-instructions': 'teacherInstructions',
  'ride-home': 'rideHome',
  'sleep-ready': 'sleepReady',
  'seeing-world': 'seeingWorld',
  'slow-breathing': 'slowBreathing',
  'smell-taste-touch': 'smellTasteTouch',
  'sort-and-dry': 'sortAndDry',
  'sort-the-harvest': 'sortTheHarvest',
  'make-and-share': 'makeAndShare',
  'snack-cleanup': 'snackCleanup',
  'snack-prep': 'snackPrep',
  'snack-table': 'snackTable',
  'spot-clean': 'spotClean',
  'shopping-list': 'supermarketList',
  'toy-cleanup': 'toyCleanup',
  'toilet-signals': 'toiletSignals',
  'toilet-steps': 'toiletSteps',
  'under-the-leaf': 'underTheLeaf',
  'prepare-the-hay': 'prepareTheHay',
  'fill-the-water': 'fillTheWater',
  'rabbit-snack-and-hop': 'rabbitSnackAndHop',
  'get-the-brush': 'getTheBrush',
  'brush-the-fur': 'brushTheFur',
  'kitten-purrs': 'kittenPurrs',
  'save-for-next-season': 'saveForNextSeason',
  'wind-and-support': 'windAndSupport',
  'welcome-the-kitten': 'welcomeTheKitten',
  'dry-the-paws': 'dryThePaws',
  'story-circle': 'storyCircle',
  'zoo-path': 'zooPath',
};

const lessonIconById: Record<string, SKidsIconName> = {
  'after-dinner-cleanup': 'clearDinner',
  'afternoon-bath': 'bathPrep',
  'afternoon-home': 'homeArrival',
  'animal-trip': 'animalGate',
  'at-school': 'classroom',
  'beach-day': 'beachSand',
  bedtime: 'bedtimeStory',
  'birthday-party': 'partyTable',
  'calm-myself': 'slowBreathing',
  'care-for-the-rabbit': 'prepareTheHay',
  'clean-muddy-paws': 'noticeMuddyPaws',
  'doctor-visit': 'clinicRoom',
  'dress-myself': 'chooseClothes',
  'family-dinner': 'dinnerTable',
  'feed-the-puppy': 'meetThePuppy',
  'find-the-kitten': 'hearTheKitten',
  'grandparents-visit': 'familyVisit',
  'five-senses': 'seeingWorld',
  'garden-friends': 'underTheLeaf',
  'garden-to-table': 'rinseAndDrain',
  'groom-the-kitten': 'getTheBrush',
  'harvest-day': 'findTheRipeOnes',
  'help-it-grow': 'newLeafSunlight',
  'lunch-time': 'lunchBox',
  'morning-routine': 'goToSchool',
  'my-body': 'headFace',
  'my-feelings': 'happySad',
  'home-play': 'homeToyCorner',
  'library-visit': 'libraryCard',
  'park-visit': 'parkEntrance',
  'personal-care': 'faceHairCare',
  'plant-a-seed': 'prepareThePot',
  'play-with-the-puppy': 'chooseTheBall',
  playtime: 'playground',
  'snack-time': 'snackPrep',
  'supermarket-trip': 'milestoneSupermarketTrip',
  'speaking-up': 'bodyBoundaries',
  'toilet-routine': 'toiletSignals',
};

const lessonMilestoneIconById: Record<string, SKidsIconName> = {
  'after-dinner-cleanup': 'milestoneAfterDinnerCleanup',
  'afternoon-bath': 'milestoneAfternoonBath',
  'afternoon-home': 'milestoneAfternoonHome',
  'animal-trip': 'milestoneAnimalTrip',
  'at-school': 'milestoneAtSchool',
  'beach-day': 'milestoneBeachDay',
  bedtime: 'milestoneBedtime',
  'birthday-party': 'milestoneBirthdayParty',
  'calm-myself': 'milestoneCalmMyself',
  'care-for-the-rabbit': 'milestoneCareForTheRabbit',
  'clean-muddy-paws': 'milestoneCleanMuddyPaws',
  'doctor-visit': 'milestoneDoctorVisit',
  'dress-myself': 'milestoneDressMyself',
  'family-dinner': 'milestoneFamilyDinner',
  'feed-the-puppy': 'milestoneFeedThePuppy',
  'find-the-kitten': 'milestoneFindTheKitten',
  'grandparents-visit': 'milestoneGrandparentsVisit',
  'five-senses': 'milestoneFiveSenses',
  'garden-friends': 'milestoneGardenFriends',
  'garden-to-table': 'milestoneGardenToTable',
  'groom-the-kitten': 'milestoneGroomTheKitten',
  'harvest-day': 'milestoneHarvestDay',
  'help-it-grow': 'milestoneHelpItGrow',
  'home-play': 'milestoneHomePlay',
  'library-visit': 'milestoneLibraryVisit',
  'lunch-time': 'milestoneLunchTime',
  'morning-routine': 'milestoneMorningRoutine',
  'my-body': 'milestoneMyBody',
  'my-feelings': 'milestoneMyFeelings',
  'park-visit': 'milestoneParkVisit',
  'personal-care': 'milestonePersonalCare',
  'plant-a-seed': 'milestonePlantASeed',
  'play-with-the-puppy': 'milestonePlayWithThePuppy',
  playtime: 'milestonePlaytime',
  'snack-time': 'milestoneSnackTime',
  'supermarket-trip': 'milestoneSupermarketTrip',
  'speaking-up': 'milestoneSpeakingUp',
  'toilet-routine': 'milestoneToiletRoutine',
};

export function getLessonIconName(lesson: Pick<Lesson, 'id'>): SKidsIconName {
  return lessonIconById[lesson.id] ?? 'map';
}

export function getLessonMilestoneIconName(
  lesson: Pick<Lesson, 'id'>,
): SKidsIconName {
  return lessonMilestoneIconById[lesson.id] ?? 'star';
}

export function getSceneIconName(scene: Pick<Scene, 'id'>): SKidsIconName {
  return sceneIconById[scene.id] ?? 'star';
}

export function getMapSceneIconName(scene: Pick<Scene, 'id'>): SKidsIconName {
  return getSceneIconName(scene);
}
