import { execFileSync } from 'node:child_process';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const assetsRoot = join(repoRoot, 'src/assets');
const registryPath = join(repoRoot, 'src/engine/GeneratedUiAudioRegistry.ts');
const backupRoot = join(assetsRoot, 'source/ui-audio-original');
const bitrate = getArgValue('--bitrate') ?? '64k';
const shouldBackup = !process.argv.includes('--no-backup');

assertFfmpegAvailable();

const registryKeys = readGeneratedUiAudioKeys();
const wavKeys = registryKeys.filter(key => key.endsWith('.wav'));
if (wavKeys.length === 0) {
  throw new Error(`No WAV UI audio entries found in ${formatRepoPath(registryPath)}`);
}

let beforeBytes = 0;
let afterBytes = 0;
let backupSourceCount = 0;

for (const wavKey of wavKeys) {
  const wavPath = join(assetsRoot, wavKey);
  if (!existsSync(wavPath)) {
    throw new Error(`Missing UI audio source: ${wavKey}`);
  }

  const backupPath = join(backupRoot, wavKey);
  if (shouldBackup && !existsSync(backupPath)) {
    mkdirSync(dirname(backupPath), { recursive: true });
    copyFileSync(wavPath, backupPath);
  }
  if (existsSync(backupPath)) {
    backupSourceCount += 1;
  }

  const mp3Path = join(assetsRoot, toOptimizedUiAudioKey(wavKey));
  mkdirSync(dirname(mp3Path), { recursive: true });

  beforeBytes += statSync(wavPath).size;
  execFileSync(
    'ffmpeg',
    [
      '-y',
      '-i',
      wavPath,
      '-codec:a',
      'libmp3lame',
      '-b:a',
      bitrate,
      '-ac',
      '1',
      '-ar',
      '24000',
      mp3Path,
    ],
    { stdio: 'ignore' },
  );
  afterBytes += statSync(mp3Path).size;
}

writeGeneratedUiAudioRegistry(registryKeys);

console.log(`Optimized ${wavKeys.length} bundled UI audio prompts`);
console.log(`Bitrate  : ${bitrate}`);
console.log(`Before   : ${formatSize(beforeBytes)}`);
console.log(`After    : ${formatSize(afterBytes)}`);
console.log(`Saved    : ${formatSaved(beforeBytes, afterBytes)}`);
if (shouldBackup) {
  console.log(`Backup   : ${backupRoot}`);
  console.log(`Source   : ${backupSourceCount}/${wavKeys.length} from backup`);
}

function readGeneratedUiAudioKeys() {
  const content = readFileSync(registryPath, 'utf8');
  const matches = Array.from(
    content.matchAll(/^\s*"([^"]+)":\s*require\("[^"]+"\),$/gmu),
  );

  if (matches.length === 0) {
    throw new Error(`Unable to parse ${formatRepoPath(registryPath)}`);
  }

  return matches.map(match => match[1]).sort();
}

function writeGeneratedUiAudioRegistry(keys) {
  const lines = [
    "import type { ImageRequireSource } from 'react-native';",
    '',
    '/** Generated by scripts/generateMissingAudio.mjs and scripts/optimizeUiAudio.mjs. Do not edit manually. */',
    'export const generatedUiAudioRegistry: Record<string, ImageRequireSource> = {',
    ...keys.map(
      key =>
        `  ${formatString(key)}: require(${formatString(
          `../assets/${getUiAudioRequireKey(key)}`,
        )}),`,
    ),
    '};',
    '',
  ];
  writeFileSync(registryPath, lines.join('\n'));
}

function getUiAudioRequireKey(key) {
  const optimizedKey = toOptimizedUiAudioKey(key);
  return existsSync(join(assetsRoot, optimizedKey)) ? optimizedKey : key;
}

function toOptimizedUiAudioKey(key) {
  return key.replace(/\.wav$/u, '.mp3');
}

function assertFfmpegAvailable() {
  try {
    execFileSync('ffmpeg', ['-version'], { stdio: 'ignore' });
  } catch {
    throw new Error('ffmpeg is required to optimize bundled UI audio.');
  }
}

function getArgValue(name) {
  const inline = process.argv.find(arg => arg.startsWith(`${name}=`));
  if (inline) {
    return inline.slice(name.length + 1);
  }

  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

function formatSaved(before, after) {
  return `${((1 - after / before) * 100).toFixed(1)}%`;
}

function formatSize(bytes) {
  return `${(bytes / 1024 / 1024).toFixed(2)} MiB`;
}

function formatString(value) {
  return JSON.stringify(value);
}

function formatRepoPath(filePath) {
  return filePath.replace(`${repoRoot}/`, '');
}
